language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: async-week--heroku-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: LH8RXBTxLYG8+EpM6DbxLnRbJb43bwz08fL60hEbgPGYv3WM6i/ZhMTem9XO55YPFz1+KCAHggbtmo07ogdhOOhTeEYlPGP80JOxqoFJjIEtgmc1S4M+glVFGiiLINpF++uYTCugUbCOsamngdCoupkB4TzJBXlea2UfC2UlHCOg9LnUAyWlY6RbqJGmRbo0eKIrpi4OqE3P59M0jU9SqrU9RsNU/TjeGT6ddSIb/fanONYKQAH3V34kQ3ykc8L7BKmnOOUHnMo8fhGxOA5kRJCXsAxesVriOBi6Fetz9VrwPjXDR16PJOap9cDdl3UOLSY+7hkzZsRJJvCBIlVel5vDORD0fa0e3GlcVNG6FhAemQEMqD/y9C5dTedyoVYlTckLD383jbud5rtP4l4CQsbm0+3VC//ilKx4LIoh9gUIztLvNA/igkYE18D5L9ma8qsR9951qdvLmZkwmwv26h8x/8WBW7up34DbiA1u5G9Cq6nBx+1wEcrX6sqZuw2xXs7HHfJ3qYo1r+ZPzPygnNXMVDyCujBdsfc2hE6WlXg20GWzOrPRUBIIon1eheJDlE8XWRSinvFsnhDMDaOis5KzeQgvc/oBwgSxbIlQCFPql2uZ+DTenHZNX4XFHBvgI7i9KxVq2x3I/CauqUMpFRy9GnC/Eip9DLfOk3OFUqA=
